companey/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('employee.urls')),
    path('', include('salary.urls')),
    path('', include('account.urls')),
    path('', include('employeesside.urls')),



]

employee/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required


urlpatterns=[

    path('employees/add/', login_required(employee_form_view), name='employee_form_view'),
    path('employees/', login_required(employees_list), name='employee-list'),
    path('employees/delete/<int:employee_id>/', login_required(delete_employee), name='delete_employee'),
    path('employees/edit/<int:employee_id>/', login_required(edit_employee), name='edit_employee'),
    
    ]

salary/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required


urlpatterns=[

    path('salary/', login_required(calculate_salary), name='calculate_salary'),
    path('salary/pay/<int:SalaryInformation_id>/', login_required(salary_pay), name='salary_pay'),
    path('salary/history/<int:employee_id>/<str:month>/', login_required(monthly_payment_history), name='monthly_payment_history'),
    path('payment/delete/<int:payment_id>/', login_required(delete_payment), name='delete_payment'),
    path('export_to_excel/', login_required(export_to_excel), name='export_to_excel'),

    ]

employee/models.py
from django.db import models
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from account.models import UserProfile


# Create your models here.
class Employee(models.Model):    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    employee_side = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15)
    address = models.TextField()
    hire_date = models.DateField(blank=True, null=True)
    marital_status = models.BooleanField(default=False)
    num_children = models.PositiveIntegerField(default=0, blank=True) 
    employee_status = models.BooleanField(default=True)

    
    def save(self, *args, **kwargs):
        if self.num_children is None:
            self.num_children = 0
        super().save(*args, **kwargs)

    

@receiver(pre_save, sender=Employee)
def update_num_children(sender, instance, **kwargs):
    if instance.pk is not None:
        try:
            old_instance = sender.objects.get(pk=instance.pk)
            if old_instance.marital_status and not instance.marital_status:
                instance.num_children = 0
        except sender.DoesNotExist:
            pass

employee/forms.py
from django import forms
from .models import Employee


class EmployeeForm(forms.ModelForm):
    """
    A form for creating or updating an Employee instance.

    The form has a number of hidden fields that are rendered as normal input
    fields, but are not editable by the user. The fields are:

    * num_children: This field is hidden if the user is not employed, or if
      the user is employed and has entered a value for num_children. If the user
      is employed but does not have a value for num_children, then the field is
      rendered as a normal number input field.
    * hire_date: This field is rendered as a date input field with a type of
      "date".
    """

    class Meta:
        model = Employee
        fields = [
            'name',
            'employee_side',
            'phone_number',
            'address',
            'hire_date',
            'marital_status',
            'num_children',
        ]

    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)
        self.fields['num_children'].widget = forms.HiddenInput()

        # If the user has submitted the form and the marital_status field
        # is checked, then render the num_children field as a normal number
        # input field. Otherwise, hide it.
        if 'marital_status' in self.data and self.data['marital_status'] == 'True':
            self.fields['num_children'].widget = forms.NumberInput()

        self.fields['hire_date'].widget = forms.DateInput(
            attrs={'type': 'date'}
        )
        self.fields['address'].widget = forms.Textarea(attrs={'style': 'width: 359px; height: 88px;'})



class EditEmployeeForm(forms.ModelForm):
    """
    A form for editing an existing Employee instance.

    This form has the same fields as the EmployeeForm, but it does not have
    the employee_side field because the employee_side field is not editable.
    """
    class Meta:
        model = Employee
        fields = [
            'name',
            'employee_side',
            'phone_number',
            'address',
            'hire_date',
            'marital_status',
            'num_children',
        ]
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['hire_date'].widget = forms.DateInput(
            attrs={'type': 'date'}
        )
        self.fields['address'].widget = forms.Textarea(attrs={'style': 'width: 359px; height: 88px;'})

employee/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse 
from .forms import EmployeeForm, EditEmployeeForm 
from .models import Employee
from account.models import UserProfile
from django.http import JsonResponse


def employee_form_view(request):
    """
    This view renders a form for creating a new employee and
    validates the data upon POST request. If the form is valid,
    it creates a new Employee object and redirects to the list view.
    """
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            employee = form.save(commit=False)
            employee.user = request.user
            employee.save()
            return redirect('employee-list')
        else:
            print(form.errors)
    else:
        # Get all unique employee_side objects from UserProfile model
        # that belongs to the logged in user
        user_employee_sides = UserProfile.objects.filter(user=request.user)
        # Create a new form instance
        form = EmployeeForm()
        # set the queryset for the employee_side field to the unique employee_side objects
        form.fields['employee_side'].queryset = user_employee_sides
        # set the label for the employee_side field to the name of the employee_side object
        form.fields['employee_side'].label_from_instance = lambda obj: "%s" % obj.employee_side

    return render(request, 'employee_form.html', {'form': form})

def edit_employee(request, employee_id):
    """
    This view renders a form for editing an existing employee object
    upon POST request, it validates the data and updates the object.
    """
    employee = get_object_or_404(Employee, pk=employee_id)
    if request.method == 'POST':
        form = EditEmployeeForm(request.POST, instance=employee)  # Pass instance here
        if form.is_valid():
            form.save()
            return redirect('employee-list')
    else:
        # Get all unique employee_side objects from UserProfile model
        # that belongs to the logged in user
        user_employee_sides = UserProfile.objects.filter(user=request.user)
        # Create a new form instance
        form = EditEmployeeForm(instance=employee)  # Pass instance here
        # set the queryset for the employee_side field to the unique employee_side objects
        form.fields['employee_side'].queryset = user_employee_sides
        # set the label for the employee_side field to the name of the employee_side object
        form.fields['employee_side'].label_from_instance = lambda obj: "%s" % obj.employee_side
        
    return render(request, 'employees_edit.html', {'form': form})

# get all employees from uniqe user
def employees_list(request):
    """
    This view renders the list of all employees that belong to the logged in user
    """
    employees = Employee.objects.filter(user=request.user)
    return render(request, 'employees_list.html', {'employees': employees})

def delete_employee(request, employee_id):
    """
    This view handles DELETE request to delete an employee object.
    It deletes the object and returns a success message in JSON format.
    """
    if request.method == 'DELETE':
        employee = get_object_or_404(Employee, pk=employee_id)
        employee.delete()
        return JsonResponse({'message': 'Employee deleted successfully.'})
    else:
        return JsonResponse({'message': 'Invalid request method.'}, status=400)

employee/templates/employee_form.html
{% extends 'base.html' %}

{% block head %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee Form</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 20px;
        }

        form {
            max-width: 400px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }

        input, select {
            width: 100%;
            padding: 8px;
            margin-bottom: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type="number"] {
            display: none;  /* initially hide the number input */
        }

        input[type="submit"]{
            background-color: #4caf50;
            color: #fff;
            cursor: pointer;
        }
        input[type="button"]{
            background-color: red;
            color: #fff;
            cursor: pointer;
        }
    </style>
    {% endblock %}


    
    {% block content %}
    <form method="post" action="{% url 'employee_form_view' %}">
    {% csrf_token %}
    
    <label for="id_name">Name:</label>
    {{ form.name }}

    <label for="id_name">Employee side:</label>
    {{ form.employee_side }}
    
    
    <label for="id_phone_number">Phone number:</label>
    {{ form.phone_number }}
    
    <label for="id_address">Address:</label>
    {{ form.address }}
    
    <label for="id_hire_date">Hire date:</label>
    {{ form.hire_date }}
     
    <label for="id_marital_status">marital_status:</label>
    {{ form.marital_status }}
    
    <label for="id_num_children" id="numChildrenLabel">Number of Children:</label>
<input type="number" name="num_children" id="id_num_children" {% if form.num_children.value %}value="{{ form.num_children.value }}"{% endif %}>

    
    <input type="submit" value="Submit">
    <input type="button" value="Cancel" onclick="window.history.back()">

</form>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var employmentStatusField = document.getElementById("id_marital_status");
        var numChildrenField = document.getElementById("id_num_children");
        var numChildrenLabel = document.getElementById("numChildrenLabel");

        function toggleNumChildrenField() {
            if (employmentStatusField.checked) {
                numChildrenField.style.display = "block";
                numChildrenLabel.style.display = "block";
            } else {
                numChildrenField.style.display = "none";
                numChildrenLabel.style.display = "none";
            }
        }

        employmentStatusField.addEventListener("change", toggleNumChildrenField);

        // If the marital_status value is pre-set, apply changes
        toggleNumChildrenField();
    });
</script>

{% endblock %}

employee/templates/employees_edit.html
{% extends 'base.html' %}

{% block head %}
    {{ block.super }}
    <style>
        /* استایل فرم */
        .form-text {
            max-width: 400px;
            margin: 20px auto; /* افزودن فاصله از بالا */
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        /* استایل ورودی‌های فرم */
        .form-text input {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        /* استایل دکمه ارسال فرم */
        .form-text button {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 15px;
            border-radius: 4px;
            cursor: pointer;
        }

        /* تغییر رنگ دکمه هنگام هاور (hover) */
        .form-text button:hover {
            background-color: #0056b3;
        }
        
        /* اضافه کردن استایل به ورودی‌های فرم هنگام فوکوس */
        .form-text input:focus {
            outline: none;
            border-color: #007bff; /* یا رنگ دلخواه برای تغییر رنگ حاشیه */
            box-shadow: 0 0 5px rgba(0, 123, 255, 0.5); /* یا هر جایگزین دیگری که دوست دارید */
        }
        
        /* استایل متن "Edit Employee" */
        .edit-employee-title {
            color: #007bff; /* یا رنگ دلخواه برای متن */
            font-size: 24px; /* یا اندازه دلخواه فونت */
            /* دیگر استایل‌های دلخواه خود را اضافه کنید */
        }
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 20px;
        }

        form {
            max-width: 400px;
            margin: 0 auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            display: block;
            margin-bottom: 8px;
            font-weight: bold;
        }

        input, select {
            width: 100%;
            padding: 8px;
            margin-bottom: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type="number"] {
            display: none;  /* initially hide the number input */
        }

        input[type="submit"]{
            background-color: #4caf50;
            color: #fff;
            cursor: pointer;
        }
        input[type="button"]{
            background-color: red;
            color: #fff;
            cursor: pointer;
        }
    </style>
{% endblock %}



{% block content %}

    <form method="post" action="">
        {% csrf_token %}
        
        <label for="id_name">Name:</label>
        {{ form.name }}
    
        <label for="id_name">Employee side:</label>
        {{ form.employee_side }}
        
        
        <label for="id_phone_number">Phone number:</label>
        {{ form.phone_number }}
        
        <label for="id_address">Address:</label>
        {{ form.address }}
        
        <label for="id_hire_date">Hire date:</label>
        {{ form.hire_date }}
         
        <label for="id_marital_status">marital_status:</label>
        {{ form.marital_status }}
        
        <label for="id_num_children" id="numChildrenLabel">Number of Children:</label>
    <input type="number" name="num_children" id="id_num_children" {% if form.num_children.value %}value="{{ form.num_children.value }}"{% endif %}>
    
        
        <input type="submit" value="Submit">
        <input type="button" value="Cancel" onclick="window.history.back()">
    
    </form>
</div>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var employmentStatusField = document.getElementById("id_marital_status");
        var numChildrenField = document.getElementById("id_num_children");
        var numChildrenLabel = document.getElementById("numChildrenLabel");

        function toggleNumChildrenField() {
            if (employmentStatusField.checked) {
                numChildrenField.style.display = "block";
                numChildrenLabel.style.display = "block";
            } else {
                numChildrenField.style.display = "none";
                numChildrenLabel.style.display = "none";
            }
        }

        employmentStatusField.addEventListener("change", toggleNumChildrenField);

        // If the marital_status value is pre-set, apply changes
        toggleNumChildrenField();
    });
</script>
{% endblock %}

employee/templates/employees_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Employees </title>

<!--TODO debug this after release
<link href="/static/css/Employees/employees.css" rel="stylesheet">
-->

	<script type="text/javascript">
		var csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value; // Setting CSRF token
	</script>
	<meta name="csrf-token" content="{{ csrf_token }}"> <!-- CSRF token -->
	<link href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css\jquery.dataTables.min.css' %}">
	<link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.min.css" rel="stylesheet">
	<link rel="stylesheet" href= "{% static 'css\tables.css' %}">


{% endblock %}
	
{% block content %}

<div class="container w-full md:w-5/6 xl:w-5/6  mx-auto px-0">
	
    <h1 class="flex items-center font-sans font-bold break-normal text-indigo-500 px-2 py-8 text-xl md:text-2xl">
        Employee List
    </h1>

	<button class="bg-blue-500 text-white font-bold py-2 px-5 rounded mr-2 btt" onclick="redirectToGoogle()">
		New Employee
		</button>

    <div id="recipients" class="p-8 mt-6 lg:mt-0 rounded shadow bg-white mytable">
		<table id="example" class="stripe hover mytable" style="width:100%; padding-top: 0em; padding-bottom: 1em;">
			<thead class="mytable">
				<tr class="mytable">
					<th>name</th>
					<th>phone_number</th>
					<th>Address</th>
					<th>hire_date</th>
					<th>marital_status</th>
					<th>num_children</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody class="mytable">
				{% for employee in employees %}
				<tr class="{% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %} " style="background-color: var(--mytable-color);color: var(--text-color);">
					<td>{{ employee.name }}</td>
					<td>{{ employee.phone_number }}</td>
					<td>{{ employee.address }}</td>
					<td>{{ employee.hire_date }}</td>
					<td>{{ employee.marital_status }}</td>
					<td>{{ employee.num_children }}</td>

					


				<td class="action-buttons">
					<button class="edit-button" onclick="openEditForm({{ employee.id }})">Edit</button>
					<button class="delete-button" data-employee-id="{{ employee.id }}">Delete</button>

				</td>
			</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
</div>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script>
	if (typeof jQuery == 'undefined') {
		console.log('jQuery is not loaded');
	} else {
		console.log('jQuery is loaded');
	}
</script>

<!--Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
        


	<script>
		$(document).ready(function() {

			var table = $('#example').DataTable({
					responsive: true
				})
				.columns.adjust().responsive.recalc();
		});
	</script>
    <script>
        function openEditForm(employeeId) {
            window.location.href = 'edit/' + employeeId + '/';
        }
    </script>

		<script>
			function redirectToGoogle() {
				window.location.href = 'add/';
			}
		</script>
		
	<script type="text/javascript">
		var csrftoken = $('input[name="csrfmiddlewaretoken"]').val();
		var csrftoken = $("meta[name='csrf-token']").attr("content");

		$.ajaxSetup({
			beforeSend: function(xhr) {
				if (!this.crossDomain) {
					xhr.setRequestHeader("X-CSRFToken", csrftoken);
				}
			},
		});
	
		$(document).ready(function () {
			$('.delete-button').on('click', function () {
				var row = $(this).closest('tr');
				var employeeId = $(this).data('employee-id');
		
				if (confirm('Are you sure you want to delete this employee?')) {
					$.ajax({
						type: 'DELETE',
						url: '/employees/delete/' + employeeId + '/',
						headers: {
							'X-CSRFToken': csrftoken
						},
						success: function () {
							var table = $('#example').DataTable();
							table.row(row).remove().draw(false); 
						},
						error: function (xhr, status, error) {
							alert('یک خطا رخ داده است، لطفاً دوباره تلاش کنید.');
						}
					});
				}
			});
		});
	</script>

{% endblock %}